//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInsuarence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int IdCustomer { get; set; }
        public Nullable<int> Age { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> UserType { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
